[2023-04-21T10:08:28.432+0000] {taskinstance.py:1084} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: task_on_table.insert_values manual__2023-04-21T10:08:27.029427+00:00 [queued]>
[2023-04-21T10:08:28.439+0000] {taskinstance.py:1084} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: task_on_table.insert_values manual__2023-04-21T10:08:27.029427+00:00 [queued]>
[2023-04-21T10:08:28.440+0000] {taskinstance.py:1282} INFO - 
--------------------------------------------------------------------------------
[2023-04-21T10:08:28.440+0000] {taskinstance.py:1283} INFO - Starting attempt 1 of 1
[2023-04-21T10:08:28.441+0000] {taskinstance.py:1284} INFO - 
--------------------------------------------------------------------------------
[2023-04-21T10:08:28.448+0000] {taskinstance.py:1303} INFO - Executing <Task(PostgresOperator): insert_values> on 2023-04-21 10:08:27.029427+00:00
[2023-04-21T10:08:28.452+0000] {standard_task_runner.py:55} INFO - Started process 624 to run task
[2023-04-21T10:08:28.455+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'task_on_table', 'insert_values', 'manual__2023-04-21T10:08:27.029427+00:00', '--job-id', '13', '--raw', '--subdir', 'DAGS_FOLDER/Task1.py', '--cfg-path', '/tmp/tmp9us9cpga']
[2023-04-21T10:08:28.457+0000] {standard_task_runner.py:83} INFO - Job 13: Subtask insert_values
[2023-04-21T10:08:28.508+0000] {task_command.py:388} INFO - Running <TaskInstance: task_on_table.insert_values manual__2023-04-21T10:08:27.029427+00:00 [running]> on host cb97ea8540cf
[2023-04-21T10:08:28.558+0000] {taskinstance.py:1511} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=task_on_table
AIRFLOW_CTX_TASK_ID=insert_values
AIRFLOW_CTX_EXECUTION_DATE=2023-04-21T10:08:27.029427+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-04-21T10:08:27.029427+00:00
[2023-04-21T10:08:28.559+0000] {sql.py:254} INFO - Executing: 
                INSERT INTO users VALUES
                ('amit','shukla','india','cseamit@gmail.com'),
                ('sam','curran','australia','sam@gmail.com'),
                ('Sumit','Sharma','India','sumit@gmail.com') ;    
        
[2023-04-21T10:08:28.568+0000] {base.py:73} INFO - Using connection ID 'postgres' for task execution.
[2023-04-21T10:08:28.676+0000] {base.py:73} INFO - Using connection ID 'postgres' for task execution.
[2023-04-21T10:08:28.684+0000] {sql.py:375} INFO - Running statement: 
                INSERT INTO users VALUES
                ('amit','shukla','india','cseamit@gmail.com'),
                ('sam','curran','australia','sam@gmail.com'),
                ('Sumit','Sharma','India','sumit@gmail.com') ;    
        , parameters: None
[2023-04-21T10:08:28.685+0000] {sql.py:384} INFO - Rows affected: 3
[2023-04-21T10:08:28.694+0000] {taskinstance.py:1326} INFO - Marking task as SUCCESS. dag_id=task_on_table, task_id=insert_values, execution_date=20230421T100827, start_date=20230421T100828, end_date=20230421T100828
[2023-04-21T10:08:28.748+0000] {local_task_job.py:212} INFO - Task exited with return code 0
[2023-04-21T10:08:28.766+0000] {taskinstance.py:2585} INFO - 1 downstream tasks scheduled from follow-on schedule check
