[2023-04-25T08:57:30.503+0000] {taskinstance.py:1090} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: task_on_table.insert_values manual__2023-04-25T08:57:28.946161+00:00 [queued]>
[2023-04-25T08:57:30.508+0000] {taskinstance.py:1090} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: task_on_table.insert_values manual__2023-04-25T08:57:28.946161+00:00 [queued]>
[2023-04-25T08:57:30.509+0000] {taskinstance.py:1288} INFO - 
--------------------------------------------------------------------------------
[2023-04-25T08:57:30.509+0000] {taskinstance.py:1289} INFO - Starting attempt 1 of 1
[2023-04-25T08:57:30.509+0000] {taskinstance.py:1290} INFO - 
--------------------------------------------------------------------------------
[2023-04-25T08:57:30.517+0000] {taskinstance.py:1309} INFO - Executing <Task(PostgresOperator): insert_values> on 2023-04-25 08:57:28.946161+00:00
[2023-04-25T08:57:30.521+0000] {standard_task_runner.py:55} INFO - Started process 2515 to run task
[2023-04-25T08:57:30.524+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'task_on_table', 'insert_values', 'manual__2023-04-25T08:57:28.946161+00:00', '--job-id', '124', '--raw', '--subdir', 'DAGS_FOLDER/Task1.py', '--cfg-path', '/tmp/tmps16n9w5r']
[2023-04-25T08:57:30.525+0000] {standard_task_runner.py:83} INFO - Job 124: Subtask insert_values
[2023-04-25T08:57:30.575+0000] {task_command.py:389} INFO - Running <TaskInstance: task_on_table.insert_values manual__2023-04-25T08:57:28.946161+00:00 [running]> on host d51842477fac
[2023-04-25T08:57:30.624+0000] {taskinstance.py:1518} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=task_on_table
AIRFLOW_CTX_TASK_ID=insert_values
AIRFLOW_CTX_EXECUTION_DATE=2023-04-25T08:57:28.946161+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-04-25T08:57:28.946161+00:00
[2023-04-25T08:57:30.625+0000] {sql.py:254} INFO - Executing: 
                INSERT INTO users VALUES
                ('amit','shukla','india','cseamit@gmail.com'),
                ('sam','curran','australia','sam@gmail.com'),
                ('Sumit','Sharma','India','sumit@gmail.com') ;    
        
[2023-04-25T08:57:30.632+0000] {base.py:73} INFO - Using connection ID 'postgres' for task execution.
[2023-04-25T08:57:30.735+0000] {base.py:73} INFO - Using connection ID 'postgres' for task execution.
[2023-04-25T08:57:30.740+0000] {sql.py:375} INFO - Running statement: 
                INSERT INTO users VALUES
                ('amit','shukla','india','cseamit@gmail.com'),
                ('sam','curran','australia','sam@gmail.com'),
                ('Sumit','Sharma','India','sumit@gmail.com') ;    
        , parameters: None
[2023-04-25T08:57:30.741+0000] {sql.py:384} INFO - Rows affected: 3
[2023-04-25T08:57:30.750+0000] {taskinstance.py:1332} INFO - Marking task as SUCCESS. dag_id=task_on_table, task_id=insert_values, execution_date=20230425T085728, start_date=20230425T085730, end_date=20230425T085730
[2023-04-25T08:57:30.778+0000] {local_task_job.py:212} INFO - Task exited with return code 0
[2023-04-25T08:57:30.795+0000] {taskinstance.py:2596} INFO - 1 downstream tasks scheduled from follow-on schedule check
